### ISSUE TITLE
请问依赖的版本都是什么

### ISSUE THREAD

**Issue by dpbycicle** [MarkWuNLP/MultiTurnResponseSelection#13]
Hi， 我clone下来的代码跑挂了，没弄懂什么原因：

MultiTurnResponseSelection/src/CNN.py:233: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  self.output =theano.tensor.signal.pool.pool_2d(input=conv_out_tanh, ds=self.poolsize, ignore_border=True,mode="max")
Traceback (most recent call last):
  File "SMN_Last.py", line 422, in <module>
    ,hidden_size=100,word_embedding_size=100)
  File "SMN_Last.py", line 334, in train
    train_model = theano.function([index], cost,updates=grad_updates, givens=dic,on_unused_input='ignore')
  File "/usr/lib64/python2.7/site-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/lib64/python2.7/site-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/lib64/python2.7/site-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

这个是theano的版本问题么？

**Comment by wenchaodudu** [comment]
Try insert this snippet right after line 336 in SMN_Last.py:
`    for x in range(len(grad_updates)):
        if grad_updates[x][0].dtype == 'float32':
            grad_updates[x] = (T._shared(grad_updates[x][0].eval().astype('float64')), grad_updates[x][1])
`

**Comment by wenchaodudu** [comment]
Did you config your .theanorc file? I fix the problem by setting floatX=float32
